version: "3"

services:
  wallet:
    build:
      context: https://github.com/tyagnii/gw-currency-wallet.git
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db

  exchanger:
    build:
      context: https://github.com/tyagnii/gw-exchanger.git
      dockerfile: ./Dockerfile
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres


